git:
- alias: noobaa-core
  automerge: 'yes'
  branch: 5.11
  commit: 4ea978db9f97de067526160b55af56c288sdsd05640
  url: https://github.com/noobaa/noobaa-core.git
- alias: noobaa-operator
  automerge: 'yes'
  branch: 5.11
  commit: 8d6f6d37bc708789e19cd51ab584a20sdsdbc4ff9
  url: https://github.com/noobaa/noobaa-operator.git
- alias: ceph-csi
  automerge: 'yes'
  branch: release-4.11
  commit: 56cf5b8f5860b9a433136a6131db77a1c41199b4
  url: https://github.com/red-hat-storage/ceph-csi
- alias: ocs-operator
  automerge: 'yes'
  branch: release-4.11
  commit: c3b5d924eccbe081ae86d8cb6781161afdff3ef8
  url: https://github.com/red-hat-storage/ocs-operator
- alias: rook
  automerge: 'yes'
  branch: release-4.11
  commit: 6c76d4c259ba1d510ef654fa3e8ae48999148eee
  url: https://github.com/red-hat-storage/rook
- alias: volume-replication-operator
  automerge: 'yes'
  branch: release-4.11
  commit: 122b49b7c9fd59dc1e60ce6f5d51faf32667ed92
  url: https://github.com/red-hat-storage/volume-replication-operator
- alias: odf-operator
  automerge: 'yes'
  branch: release-4.11
  commit: f3416507a1c3084ee132bcb43ea3f3291cddff08
  url: https://github.com/red-hat-storage/odf-operator
- alias: odf-console
  automerge: 'yes'
  branch: release-4.11
  commit: 6b67b988c99a8297f62904719ba1d4008ff5e70a
  url: https://github.com/red-hat-storage/odf-console
- alias: odf-console-compatibility
  automerge: 'yes'
  branch: release-4.10-compatibility
  commit: 27dd9e5c4dc820c18634ad9b1122689a656e5cd5
  url: https://github.com/red-hat-storage/odf-console
- alias: odf-multicluster-orchestrator
  automerge: 'yes'
  branch: release-4.11
  commit: a15158432ec85d453abda9d6a6ebf9165be15a1e
  url: https://github.com/red-hat-storage/odf-multicluster-orchestrator
- alias: ramen
  automerge: 'yes'
  branch: release-4.11
  commit: 2364f76cec4cc2dcd5476c33835a7743773f3c21
  url: https://github.com/red-hat-storage/ramen
- alias: lvm-operator
  automerge: 'yes'
  branch: release-4.11
  commit: 72dfd6d9c18498b63f1d45746b084f3cbc5b3904
  url: https://github.com/red-hat-storage/lvm-operator
- alias: topolvm
  automerge: 'yes'
  branch: release-4.11
  commit: 1d5185d02c64d5b5825737c8d6ebf641669bfff3
  url: https://github.com/red-hat-storage/topolvm
- alias: kubernetes-csi-addons
  automerge: 'yes'
  branch: release-4.11
  commit: c69620f6086a6dfd0b790788ed2000455b2a8b5b
  url: https://github.com/red-hat-storage/kubernetes-csi-addons
